---

R1:
    hostname: "10.0.0.21"
    groups:
        - cisco_group
    data:
        dmvpn: yes

R2:
    hostname: "10.0.0.22"
    groups:
        - cisco_group
    data:
        dmvpn: yes

R3:
    hostname: "10.0.0.23"
    groups:
        - cisco_group
    data:
        dmvpn: yes

R4:
    hostname: "10.0.0.24"
    groups:
        - cisco_group
    data:
        dmvpn: yes
        