---

R1:
    hostname: "10.0.0.11"
    groups:
        - euro_group
        - cisco_group

R2:
    hostname: "10.0.0.12"
    groups:
        - usa_group
        - cisco_group

R3:
    hostname: "10.0.0.13"
    groups:
        - euro_group
        - cisco_group

R4:
    hostname: "10.0.0.14"
    groups:
        - usa_group
        - cisco_group