---

R1:
    hostname: "10.0.0.21"
    groups:
        - cisco_group

R2:
    hostname: "10.0.0.22"
    groups:
        - cisco_group

R3:
    hostname: "10.0.0.23"
    groups:
        - cisco_group

R4:
    hostname: "10.0.0.24"
    groups:
        - cisco_group

R5:
    hostname: "10.0.0.25"
    groups:
        - cisco_group

R6:
    hostname: "10.0.0.26"
    groups:
        - cisco_group

R7:
    hostname: "10.0.0.27"
    groups:
        - junos_group